on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  on-develop-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:                       # ここからjobの中で実行されるコマンドですよーという意味
      - name: Hello World        # stepは一つ一つ名前がつけることができます（つけておくとどこで失敗したのかがわかりやすくなります）
        run: echo "Hello World"  # 実行されるコマンド、echoでHello Worldを表示
